# Generated by Django 3.1.7 on 2021-04-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210402_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='etime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='stime',
            field=models.TimeField(blank=True),
        ),
    ]
