# Generated by Django 3.1.7 on 2021-04-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210403_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='etime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='sdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='stime',
            field=models.TimeField(),
        ),
    ]
