# Generated by Django 3.1.7 on 2021-04-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='note',
        ),
    ]
